[package]
name = "healpix-geo"
version = "0.0.7"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "healpix_geo"
crate-type = ["cdylib"]

[dependencies]
cdshealpix = { git = "https://github.com/cds-astro/cds-healpix-rust.git", rev = "79879d9c12343a3d162c2e3e00687f5ded41bdb8", version = "0.8.1" }
moc = "0.18.0"
geodesy = "0.14.0"
ndarray = { version = "0.17.1", features = ["rayon"] }
numpy = "0.27.0"
pyo3 = "0.27.1"
rayon = "1.11.0"
