[package]
name = "healpix-geo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "healpix_geo"
crate-type = ["cdylib"]

[dependencies]
cdshealpix = { version = "0.7.3", git = "https://github.com/keewis/cds-healpix-rust.git", branch = "kth-ring-neighbours" }
ndarray = { version = "0.16.1", features = ["rayon"] }
numpy = "0.23.0"
pyo3 = "0.23.3"
rayon = "1.10.0"
